### ISSUE TITLE
`browsingContext.navigationStarted` tracker 

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#1054]
- [ ] Initial implementation at #1009
- [ ] Should support url - should be possible with a CDP change
- [ ] Should support navigationId - on practice the loaderId should be created at this point but not sure how easy it would be be propaginated

**Comment by christian-bromann** [comment]
@Lightning00Blade any updates on this? Having the navigation id for sub requests is very helpful to provide detailed information about all requests connected to a navigate command.

**Comment by Lightning00Blade** [comment]
Marking it as complete as the WPT test pass.
