### ISSUE TITLE
Re-enable flaky tests disabled in Chromium CI

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#2045]
Re-enable flaky tests disabled in [Chromium CI](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/TestExpectations), namely:
* [x] external/wpt/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py [ Failure Pass ]
* [x] external/wpt/webdriver/tests/bidi/browsing_context/capture_screenshot/invalid.py [ Failure Pass ]
* [x] external/wpt/webdriver/tests/bidi/browsing_context/create/background.py [ Failure Pass ]
* [x] external/wpt/webdriver/tests/bidi/browsing_context/set_viewport/viewport.py [ Failure Pass ]
* [ ] external/wpt/webdriver/tests/bidi/network/remove_intercept/remove_intercept.py [ Failure Pass ]
* [x] external/wpt/webdriver/tests/bidi/network/response_completed/response_completed.py [ Failure Pass ]
