### ISSUE TITLE
Google Search Mapper implementation

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#263]
- [x] #239
- [ ] passing the WPT tests.
- [ ] passing WPT.fyi tests.
- [ ] passing example script.
