### ISSUE TITLE
BiDi+ commands are not aligned with the spec

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#2757]
WebDriver BiDi specification restricts vendor-specific [extension modules](https://w3c.github.io/webdriver-bidi/#extension-modules) to have a prefix, in case of Chromium it's `goog:`. Currently, [BiDi+](https://github.com/GoogleChromeLabs/chromium-bidi?tab=readme-ov-file#bidi) don't have that prefixes, which makes the implementation not spec compliant. 

* [x] https://github.com/GoogleChromeLabs/chromium-bidi/issues/2840
* [x] https://github.com/GoogleChromeLabs/chromium-bidi/issues/2841
* [x] https://github.com/GoogleChromeLabs/chromium-bidi/issues/2842
* [x] https://github.com/GoogleChromeLabs/chromium-bidi/issues/2843
* [x] https://github.com/GoogleChromeLabs/chromium-bidi/issues/2844

**Comment by anshikavashistha** [comment]
@sadym-chromium I want to work on this issue .Please assign me

**Comment by sadym-chromium** [comment]
> @sadym-chromium I want to work on this issue .Please assign me

This is an umbrella issue. Please choose a specific issue you plan to work on.

**Comment by anshikavashistha** [comment]
Thank you @sadym-chromium for letting me know
