### ISSUE TITLE
Align navigation with the spec

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#2856]
> [!IMPORTANT]
> ### 🚚 Moved to [crbug.com/411434924](https://crbug.com/411434924)
> Please star and follow **[crbug.com/411434924](https://crbug.com/411434924)** on the Chromium Issue Tracker for updates.

---

Currently, the navigation events are based on [some CDP heuristics](https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/bidiMapper/modules/context/BrowsingContextImpl.ts#L85-L106), which do not always allow for proper events  emitting and commands results.

### Related documents
* [Chromium BiDi navigation overview](http://goto.google.com/webdriver:bidi-navigation)
* [Detect navigation started](http://goto.google.com/webdriver:detect-navigation-started)
* [Deterministic random values](http://go/webdriver:deterministic-random-values)

### WPT
* [x] [`browsingContext.navigate`](https://wpt.fyi/results/webdriver/tests/bidi/browsing_context/navigate?label=master&product=chrome%5Bexperimental%5D&product=firefox&aligned=)
* [x] [`browsingContext.navigationStarted`](https://wpt.fyi/results/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py?label=master&product=chrome%5Bexperimental%5D&product=firefox&aligned=)
* [x] [browsingContext.navigationFailed](https://wpt.fyi/results/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py?label=master&product=chrome%5Bexperimental%5D&product=firefox&aligned)
* [ ] Add tests for [`browsingContext.navigationAborted`](https://w3c.github.io/webdriver-bidi/#event-browsingContext-navigationAborted)

**Comment by OrKoN** [comment]
Is https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/bidiMapper/modules/cdp/CdpTarget.ts#L244C9-L248C53 still required?

**Comment by sadym-chromium** [comment]
Moved to [crbug.com/411434924](https://crbug.com/411434924)
Please star and follow [crbug.com/411434924](https://crbug.com/411434924) on the Chromium Issue Tracker for updates.
