### ISSUE TITLE
Implement: `browsingContext.captureScreenshot`

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#514]
- Docs: https://w3c.github.io/webdriver-bidi/#command-browsingContext-captureScreenshot
- CDP: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot

## Tracking

- [x] Spec subsubsubsection 7.2.3.1
- [x] WPT tests: `/webdriver/tests/bidi/browsing_context/capture_screenshot/*`
- [x] Add implementation to Command Processor
- [x] Associated CDP command: [`Page.captureScreenshot`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot) -> need viewport
- [x] Underneath mechanism: `/session/{id}/screenshot` (via WebDriver) --> this is merely an implementation detail
- [x] Add sample gradient golden page for testing --> use it to compare (base64-wise) with the implementation -> canvas.base64
- [x] Implement `scrollIntoView`
- [x] Closed frames
- [x] https://github.com/GoogleChromeLabs/chromium-bidi/pull/580
- [x] Height is slightly different in WPT tests. Maybe it's related to the Chromium bar (automated software) or display differences: https://github.com/GoogleChromeLabs/chromium-bidi/issues/547
- [x] Finish milestone: https://github.com/GoogleChromeLabs/chromium-bidi/milestone/4
  - [x] ~~iframes: set [`captureBeyondViewport`](https://github.com/GoogleChromeLabs/chromium-bidi/issues/514#issuecomment-1470303113) to true~~
  - [x] ~~Tab focus: https://github.com/GoogleChromeLabs/chromium-bidi/pull/796~~
  - [x] Tab focus: Focus originally focused tab after taking the screenshot, or change the spec: https://github.com/w3c/webdriver-bidi/issues/171 / https://github.com/w3c/webdriver-bidi/issues/440
  - [x] Throw error on unsupported edge cases, as per the spec: ~~https://github.com/GoogleChromeLabs/chromium-bidi/pull/797~~ / https://github.com/w3c/webdriver-bidi/issues/441
  - [x] Re-enable headful screenshot tests, if at all possible: https://github.com/GoogleChromeLabs/chromium-bidi/pull/813, https://github.com/GoogleChromeLabs/chromium-bidi/pull/823 and https://github.com/web-platform-tests/wpt/pull/40382 
https://github.com/GoogleChromeLabs/chromium-bidi/blob/ebe71327d460e763c5f777afeeea1820963320ca/wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/frame.py.ini#L2 and https://github.com/GoogleChromeLabs/chromium-bidi/blob/ebe71327d460e763c5f777afeeea1820963320ca/wpt-metadata/mapper/headful/webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py.ini#L2
  - [x] Add e2e test for #851 -> setViewport to X , Y go to page that the height is bigger then Y, screenshot should match X , Y
  - [x] https://bugs.chromium.org/p/chromium/issues/detail?id=1277272: Incorrect trace screenshot dimensions with `--enable-automation`
  - [x] https://bugs.chromium.org/p/chromium/issues/detail?id=32667: Support background screenshots

## Obsolete
- ~Implement subframe `captureScreenshot`~

**Comment by thiagowfx** [comment]
Notes from meeting:

- Spec subsubsubsection 7.2.3.1
- WPT tests: `/webdriver/tests/bidi/browsing_context/capture_screenshot/*`
- Add implementation to Command Processor
- Associated CDP command: [`Page.captureScreenshot`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot) -> need viewpoer
- Add sample gradient golden page for testing --> use it to compare (base64-wise) with the implementation -> canvas.base64
- Underneath mechanism: `/session/{id}/screenshot` (via WebDriver)

**Comment by thiagowfx** [comment]
See also: https://github.com/web-platform-tests/wpt/pull/37454/

**Comment by sadym-chromium** [comment]
WPT headful test is failing. I temporary disabled it in https://github.com/GoogleChromeLabs/chromium-bidi/pull/548

**Comment by sadym-chromium** [comment]
DevTools has functionality to capture node screenshot. What it does is:
1. Call `callFunctionOn(node)` with script:
```
function(){
   const e=this.getBoundingClientRect(),
   t=this.ownerDocument.documentElement.getBoundingClientRect();
   return JSON.stringify({
      x:e.left-t.left,
      y:e.top-t.top,
      width:e.width,
      height:e.height,scale:1})}
```

And call `Page.captureScreenshot` with the following params:
```
{
  "format": "png",
  "quality": 100,
  "fromSurface": true,
  "captureBeyondViewport": true,
  "clip": { 
      RECEIVED_VALUES
  }
}
```

**Comment by sadym-chromium** [comment]
The comment above could help implementing the nested frame screenshot.

**Comment by thiagowfx** [comment]
References:

- https://github.com/puppeteer/puppeteer/pull/7063/files

**Comment by thiagowfx** [comment]
@sadym-chromium:

`const e = this.getBoundingClientRect()` seems to be

```
const metrics = await this.#cdpTarget.cdpClient.sendCommand(
  'Page.getLayoutMetrics'
);
```

**Comment by thiagowfx** [comment]
Debugging:

```
async captureScreenshot(): Promise<BrowsingContext.CaptureScreenshotResult> {
    // XXX: Either make this a proposal in the BiDi spec, or focus the
    // original tab right after the screenshot is taken.
    // The screenshot command gets blocked until we focus the active tab.
    await this.#cdpTarget.cdpClient.sendCommand('Page.bringToFront'); // window.focus() also works

    const docRect = await this.#cdpTarget.cdpClient.sendCommand(
      'Runtime.callFunctionOn',
      {
        functionDeclaration: `() => {
        const docRect = window.documentElement.getBoundingClientRect();
        return JSON.stringify({
          x: docRect.left,
          y: docRect.top,
        });
      }`,
        executionContextId: this.#defaultRealm.executionContextId,
      }
    );
    const {result: docRectResult} = docRect;
    console.log(docRectResult);

    const metrics = await this.#cdpTarget.cdpClient.sendCommand(
      'Page.getLayoutMetrics'
    );
    // or maybe cssLayoutViewport
    const {cssContentSize: viewport} = metrics;

    debugger;

    const [result] = await Promise.all([
      this.#cdpTarget.cdpClient.sendCommand('Page.captureScreenshot', {
        format: 'png', // XXX: add more formats: jpeg,webp, then add quality for jpeg
        captureBeyondViewport: true,
        clip: {...viewport, scale: 1.0},
      }),
    ]);
    return {
      result: {
        data: result.data,
      },
    };
  }
```

**Comment by thiagowfx** [comment]
More debugging:

```ts
async captureScreenshot(): Promise<BrowsingContext.CaptureScreenshotResult> {
    // XXX: Either make this a proposal in the BiDi spec, or focus the
    // original tab right after the screenshot is taken.
    // The screenshot command gets blocked until we focus the active tab.
    await this.#cdpTarget.cdpClient.sendCommand('Page.bringToFront'); // window.focus() also works

    const docRect = await this.#cdpTarget.cdpClient.sendCommand(
      'Runtime.callFunctionOn',
      {
        functionDeclaration: `() => { return JSON.stringify(globalThis.document.documentElement.getBoundingClientRect()); }`,
        executionContextId: this.#defaultRealm.executionContextId,
      }
    );
    console.log(docRect);

    const metrics = await this.#cdpTarget.cdpClient.sendCommand(
      'Page.getLayoutMetrics'
    );
    // or maybe cssLayoutViewport
    const {cssContentSize: viewport} = metrics;

    debugger;

    const [result] = await Promise.all([
      this.#cdpTarget.cdpClient.sendCommand('Page.captureScreenshot', {
        format: 'png', // XXX: add more formats: jpeg,webp, then add quality for jpeg
        captureBeyondViewport: true,
        clip: {...viewport, scale: 1.0},
      }),
    ]);
    return {
      result: {
        data: result.data,
      },
    };
  }
```

**Comment by thiagowfx** [comment]
> Implement scrollIntoView

This one can be closed, as it was removed from the BiDi spec.
