### ISSUE TITLE
Implement `Input` module

### ISSUE THREAD

**Issue by jrandolf-2** [GoogleChromeLabs/chromium-bidi#749]
Spec: https://w3c.github.io/webdriver-bidi/#module-input

## Tracking

- [x] Implementation
  - [x] Initial implementation
    - [x] https://github.com/GoogleChromeLabs/chromium-bidi/pull/784 
    - [x] https://github.com/GoogleChromeLabs/chromium-bidi/pull/782
    - [x] https://github.com/GoogleChromeLabs/chromium-bidi/pull/781 
    - [x] https://github.com/GoogleChromeLabs/chromium-bidi/pull/780
    - [x] https://github.com/GoogleChromeLabs/chromium-bidi/pull/750
      - This breaks https://github.com/web-platform-tests/wpt/blob/5db1f8e9ad325bef573d36574b36c38640d70f40/webdriver/tests/bidi/input/perform_actions/invalid.py#L164
- [x] WebDriver
  - [x] https://github.com/w3c/webdriver/issues/1457
    - [x] https://github.com/web-platform-tests/wpt/pull/40992
  - [x] https://github.com/w3c/webdriver/issues/1741 (this is a noop)
  - [ ] https://github.com/w3c/webdriver-bidi/pull/666
  - [x] https://github.com/w3c/webdriver-bidi/pull/667
- [ ] WPT
  - [x] https://github.com/web-platform-tests/wpt/pull/40106
  - [x] https://github.com/web-platform-tests/wpt/pull/40101
  - [x] https://github.com/web-platform-tests/wpt/pull/40115
  - [ ] Missing tests
      - [x] /webdriver/tests/bidi/input/perform_actions/key.py/test_key_codepoint[\u0ba8\u0bbf]
         https://github.com/web-platform-tests/wpt/pull/46019
      - [x] /webdriver/tests/bidi/input/perform_actions/key.py/test_key_codepoint[\u1100\u1161\u11a8]
         https://github.com/web-platform-tests/wpt/pull/46019
      - [x] ~/webdriver/tests/bidi/input/perform_actions/pointer_mouse_multiclick.py/test_dblclick_at_coordinates[200-False]~
      - [x] /webdriver/tests/bidi/input/perform_actions/pointer_pen.py/test_pen_pointer_properties
         1. `pointermove` should not be emitted before the pen is detected (`pointerdown`)
         2. `pointerleave` should be emitted after `pointerup` in case of the pen.
         * https://g-issues.chromium.org/issues/40539182
         * https://g-issues.chromium.org/issues/41494215
      - [x] /webdriver/tests/bidi/input/perform_actions/wheel.py/test_scroll_iframe ([0-10], [5-0], [5-10])
         * The problem is in the fact that the dom event is emitted 15 ms after CDP `Input.dispatchMouseEvent` command is finished. This makes the test failing, as the events are not yet emited when requested.
/webdriver/tests/bidi/input/release_actions/sequence.py/test_release_mouse_sequence_resets_dblclick_state[without release actions]
      - [x] /webdriver/tests/bidi/input/set_files/files.py/test_set_files_twice_same
      - [x] /webdriver/tests/bidi/input/set_files/invalid.py/test_params_element_invalid_shared_reference_value
      - [x] /webdriver/tests/bidi/input/set_files/invalid.py/test_params_element_non_input[&lt;a id='test' href='#'&gt;foo&lt;/a&gt;]
      - [x] /webdriver/tests/bidi/input/set_files/invalid.py/test_params_element_non_input[&lt;div id='test'&gt;foo&lt;/div&gt;]
      - [x] /webdriver/tests/bidi/input/set_files/invalid.py/test_params_element_non_input[&lt;span id='test' href='#'&gt;foo&lt;/span&gt;]
      - [ ] [/wpt/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py/test_move_to_origin_position_within_frame](https://github.com/web-platform-tests/wpt/blob/d2a48b9455dd6436a65e8690b21b2ac425061282/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py#L322) [Issue](https://github.com/GoogleChromeLabs/chromium-bidi/issues/2630).

**Comment by Lightning00Blade** [comment]
Closing as the WPT test were fixed. The open spec issue should be look into further @sadym-chromium
